const drivers = [
  {
    Name: "Michael Schumacher",
    title: "MSC",
    carColor: "#ff0000",
    secondary: "#ffffff",
    helmet: " #800000",
    car: "F2004",
    tier: 1,
  },
  {
    Name: "Lewis Hamilton",
    title: "HAM",
    carColor: "#000000",
    secondary: "#a6a6a6",
    helmet: " #000066",
    car: "W11",
    tier: 1,
  },
  {
    Name: "Jenson Button",
    title: "BUT",
    carColor: "#d9d9d9",
    secondary: "#ccff33",
    helmet: " #ff3300",
    car: "BGP001",
    tier: 2,
  },
  {
    Name: "Sebastian Vettel",
    title: "VET",
    carColor: "#ff0000",
    secondary: "#ffffff",
    helmet: " #ffcc00",
    car: "SF71H",
    tier: 1,
  },
  {
    Name: "Ayrton Senna",
    title: "SEN",
    carColor: "#e6e6e6",
    secondary: "#ff5c33",
    helmet: " #009900",
    car: "MP4/4",
    tier: 1,
  },
  {
    Name: "Charles Leclerc",
    title: "LEC",
    carColor: "#ff3300",
    secondary: "#000000",
    helmet: " #ff3300",
    car: "F1-75",
    tier: 2,
  },
  {
    Name: "Max Verstappen",
    title: "VER",
    carColor: "#001a33",
    secondary: "#ff6600",
    helmet: " #ff6600",
    car: "RB18",
    tier: 2,
  },
];

export default drivers;
